CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_TRACKPAD=y
CONFIG_ZMK_TRACKPAD_FINGERS=5
CONFIG_ZMK_TRACKPAD_PHYSICAL_X=400
CONFIG_ZMK_TRACKPAD_PHYSICAL_Y=400
CONFIG_ZMK_TRACKPAD_LOGICAL_X=4095
CONFIG_ZMK_TRACKPAD_LOGICAL_Y=4095
CONFIG_ZMK_SLEEP=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=4096
