file_format: "1"
id: corne_tp_og
name: Corne TP OG
type: shield
url: https://github.com/tomjihoonkwon/cross_corne
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - corne_tp_og_left
  - corne_tp_og_right
