manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: george-norton
      url-base: https://github.com/george-norton
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll-ptp
      import: app/west.yml
    - name: maxtouch-zephyr-module
      remote: george-norton
      revision: main
  self:
    path: config
